# Generated by Django 5.1 on 2024-08-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=25)),
                ('Author', models.CharField(max_length=50)),
                ('BooksFormat', models.CharField(max_length=50)),
            ],
        ),
    ]
